title: Lew Lefton
description: "Mathematician. Comedian. Maker. IT Leader."
url: "https://lewlefton.com"
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "publications"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "comedy"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
collections:
  publications:
    output: true
    permalink: /academic/:path/
  comedy:
    output: true
    permalink: /comedy/:path/
  projects:
    output: true
    permalink: /making/:path/
author:
  name: Lew Lefton
  bio: "My multifaceted life in STEM, Humor, and Making."
  location: "Decatur, GA"
